### ISSUE TITLE
Summarize the Bug/Issue Here

### ISSUE THREAD

**Issue by Svytoi2008** [surfbryce/beautiful-lyrics#1186]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

![Image](https://github.com/user-attachments/assets/a759d510-cea1-47ef-8249-f8d91d1abd2e) 

![Image](https://github.com/user-attachments/assets/84fefacd-480a-4c4f-9d39-4cab2d43b3fb)

### What Country are you from?

Russia local vpn(germany) wireguard

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

![Image](https://github.com/user-attachments/assets/ed14879d-9798-4170-a15b-755e8a3ba9c3)

![Image](https://github.com/user-attachments/assets/34fb4786-f42e-4c03-a041-6ba07f1ee7da)

### Spotify HTML/CSS and Console Screenshots

![Image](https://github.com/user-attachments/assets/62ab840f-c0ec-4a96-a79f-83b8d804a2a6) 
(https://mega.nz/folder/FD8HSDQC#t3xFq6SuPdJyYuPzrroxtw (css html)

![Image](https://github.com/user-attachments/assets/424cde3c-f247-44ca-85d5-ff2fcb732853)

### Information Checklist

- [x] Spotify/Spicetify Information
- [x] Spotify HTML File
- [x] Spotify CSS File
- [x] Screenshots of Developer Tools Console Tab

**Comment by Svytoi2008** [comment]
Переустановил виндовс 2 раза уже с английской версиии на русскую и с русской версии на английскую (USA) (Russia)

**Comment by Svytoi2008** [comment]
Reinstalled Windows 2 times: from the English version to Russian and from the Russian version to English (USA) (Russia)

**Comment by Svytoi2008** [comment]
previously, everything was fine)

**Comment by Svytoi2008** [comment]
a small request (you can throw off the link to the manual installation instructions)

**Comment by Spikerko** [comment]
@Svytoi2008 Add this Custom CSS Snippet:

```css
.Root__main-view:has(.BeautifulLyricsPage),
.KL8t9WB65UfUEPuTFAhO,
.main-content-view,
.main-view-container,
.main-view-container__scroll-node,
.main-view-container .div[data-overlayscrollbars-viewport] {
  height: 100% !important;
}
```

This may be too much force on setting the height, but it works.
