### ISSUE TITLE
(Suggestion) Hide Background Toggle

### ISSUE THREAD

**Issue by Aeropro4** [surfbryce/beautiful-lyrics#157]
can ya pls implement the thing mentioned above or guide to how to disable it.

**Comment by surfbryce** [comment]
There is no way you can remove the background without modifying the code as is.

I talked about adding a toggle with somebody when this extension first came out when they raised performance concerns after the lyrics update came out.

The background is the main performance crunch. Ideally, I like to keep the Apple way of thinking which is that you always be able to have the best looking thing across every device without losing anything.

Of course with the way the background is currently done it uses up some juice, I'm working on optimizations that change the way the background is done. For example, pre-blurring the background so that it's not done on every frame.

So, if I can get these optimizations to drastically improve the performance then this toggle won't be needed unless you simply don't like the background. Then I can make it just a solid color.

**Comment by Aeropro4** [comment]
> There is no way you can remove the background without modifying the code as is.
> 
> I talked about adding a toggle with somebody when this extension first came out when they raised performance concerns after the lyrics update came out.
> 
> The background is the main performance crunch. Ideally, I like to keep the Apple way of thinking which is that you always should be able to have the best looking thing across every device without losing anything.
> 
> Of course with the way the background is currently done it uses up some juice, I'm working on optimizations that change the way the background is done. For example, pre-blurring the background so that it's not done on every frame.
> 
> So, if I can get these optimizations to drastically improve the performance then this toggle won't be needed unless you simply don't like the background. Then I can make it just a solid color.

No Bro problem is not the performance cause i have Intel uhd 620 graphics but thge problem is this
![image](https://github.com/surfbryce/beautiful-lyrics/assets/113044496/95534c16-15d8-4307-b1a7-7588ef291450)

I have custom theme set with a background and if i remove ur extension then the background may extend to the Now Playing View but the visuals hides it and i loves the lyrics animation hence i wanted only the visuals to be removed if possible

**Comment by Aeropro4** [comment]
umm is this request list on ur list?

**Comment by im-h** [comment]
If you have a custom theme and are able to modify the css file add this if you don't want the background image on the sidebar
`.Root__right-sidebar .BeautifulLyricsBackground-Container * {
    display: none;
}`

Or add this if you don't want the background image at all
`.BeautifulLyricsBackground-Container * {
    display: none;
}`

**Comment by Aeropro4** [comment]
Yeah it works Thx!

**Comment by surfbryce** [comment]
@Aeropro4 Going to reopen this because the main reason for this to exist is still valid and people still want it

**Comment by Satanarious** [comment]
I have a couple of suggestions:
- Toggle for the background, obviously.
	- Separate toggles for NPV & Lyrics Page.
- Ability to change the background of lyrics container.
	- Set it to an image.
	- Set it to a solid colour.
	- Set it to the extracted colour from cover art.

Here's are the snippets I'm currently using to achieve few of the above mentioned behaviour:

### Add an image as background of the lyrics container in NPV
```css
/* Beautiful Lyrics Tweaked*/
#BeautifulLyrics-CardView{
  position:relative;
}
/* Add Lyrics Background*/
#BeautifulLyrics-CardView::before{
 content: "";
 top: 0;
 left: 0;
 width: 100%;
 height: 100%;
 opacity: 0.18;
 z-index: -1;
 border-radius: 10px;
 position:absolute;
/*background:url(https://media.tenor.com/t3j_zjBVoboAAAAj/snow.gif);*/
background:url(https://media.tenor.com/bx7hbOEm4gMAAAAj/sakura-leaves.gif);

 background-repeat: no-repeat;
 background-size: cover;
}

/* Remove NPV Background*/
div.BeautifulLyricsPage.Contained.lyrics-background > div.lyrics-background-container{
  display:none;
}
```

### Disable Background on NPV and Lyrics Page
```css
/* Disable Beautiful Lyrics Background*/
.Root__right-sidebar .BeautifulLyricsBackground-Container .BackCenter,
.Root__right-sidebar .BeautifulLyricsBackground-Container .Front,.BeautifulLyricsBackground-Container .Back,
.BeautifulLyricsBackground.BeautifulLyricsPage:not(.Fullscreen) .BeautifulLyricsBackground-Container
{
display:none;
}
```
