### ISSUE TITLE
Cannot click into the theatre mode

### ISSUE THREAD

**Issue by miracles1677** [surfbryce/beautiful-lyrics#935]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

The button for the cinema mode appears, but i cannot click into it for some reason, happens across my windows and mac devices, just wanted to know how to fix it if i can or if its a bug of some sort. 
can't click into it but the option for it is there. 
![image](https://github.com/user-attachments/assets/66191e35-f213-41e0-aab6-5f6fb41f2120)

### What Country are you from?

Australia

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Spotify Version: 1.2.48.405.gf2c48e6f
Spotify Runtime: cef_128.4.12+g1d7a1f9+chromium-128.0.6613.138
Spicetify Version: 2.38.4
Spicetify Theme: Ziro / blue-dark
Spicetify Extensions: [songstats.js, fullAppDisplay.js, quickQueue.js, beautiful-lyrics.mjs, fullScreenWrapper.js]
Spicetify Custom Apps: [marketplace, lyrics-plus]

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/user-attachments/assets/2dfbff4f-b85e-40ee-afeb-8eec8f131d67)
[Spotify.zip](https://github.com/user-attachments/files/17472002/Spotify.zip)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by Alehaaaa** [comment]
## I originally posted this in https://github.com/surfbryce/beautiful-lyrics/issues/965#issuecomment-2471612261

[...] fixes for the Maximize and Close buttons in the **Now playing view** and **Lyrics Page**:

```css
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}

.Root__main-view:has(.BeautifulLyricsPage) .main-view-container__scroll-node-child,
div.os-host:has(.BeautifulLyricsPage) .main-view-container__scroll-node-child {
    pointer-events: auto !important;
}
#BeautifulLyrics-CardView .Header .Controls button {
    cursor: pointer;
}
```

Also, if you are using Spotify in a vertical window with **Cinema Mode**, which will show the Spotify UI behind the background gradient, this will do the trick to hide it. _Immmersive_
```css
.BeautifulLyricsBackground.BeautifulLyricsPage.Fullscreen .BeautifulLyricsBackground-Container {
    background-color: black;
}
```
