### ISSUE TITLE
Lyrics fade out on top and bottom apart from current line

### ISSUE THREAD

**Issue by sourya2007** [surfbryce/beautiful-lyrics#943]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

I got the idea from Apple Music lyrics UI, I felt it would make the already fantastic beautiful-lyrics more beautiful🫡😉 

### What is your Suggestion?

An ability to control the fade out effect of the lyrics apart from the current lyric line i.e the top and bottom. I personally feel it would look a lot more better if the top part (lyric lines already passed through) was completely invisible and only the next three lines after the current line were shown at the bottom (quite like apple music lyrics). The glow effect and the smooth rolling is already beautiful and 10/10, the only downside I personally feel is that huge list of lines on the screen, if possible could there be a way to make it less cluttered and down to only 4-5 lines as mentioned above, Thanks a lot
![Screenshot 2024-10-27 101707](https://github.com/user-attachments/assets/772870b5-be2f-4051-996a-19a158164404)
![Screenshot 2024-10-27 101604](https://github.com/user-attachments/assets/dc3fa3fa-18e7-4f85-9397-1521e85e36a2)

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by DomBom16** [comment]
As a temporary fix, you can create a snippet and attach the following CSS:
```css
button:has(> .Sung):not(:has(> :not(.Sung))) {
    opacity: 0;
    transition: all 200ms ease-in-out;
}
```
This CSS hides all vocal groups where all elements are sung.

**Comment by DomBom16** [comment]
@sourya2007 The snippet's a bit janky, but it'll have to do until it gets added with TypeScript.
```css
.VocalsGroup {
    /* Override current transition */
    /* A delay of 200ms is added to avoid flickering */
    transition: all 200ms 200ms ease-in-out !important;
}

.LyricsScrollContainer:not(:hover) .VocalsGroup:has(> .Sung):not(:has(> :not(.Sung))), /* Lyrics already sung */
/* Lyrics that are more than 2 lyrics in advance */
.LyricsScrollContainer:not(:hover) .VocalsGroup:has(.Active) ~ .VocalsGroup ~ .VocalsGroup ~ .VocalsGroup {
    opacity: 0;
}
```
The snippet wont show lyrics before the current one and only shows the following two.
